# -*- coding: utf-8 -*-
"""Surprise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SR0aW-__jfY8p5yl4IJL7pU36q3EvAx-
"""

for i in range(7):
 for j in range(5):
  if ((i==0) and j!=0) or (i==3)  or ((i==6) and(j!=4)) or ((i==4 or i==5) and(j==4)) or((i==1 or i==2)and j==0) :
   print("*",end="")
  else:
   print(end=" " )
 print()
print("\n")
for row in range(7):
    for col in range(5):
        if ((col==0 or col==4) and row!=0)or ((row==0 or row==3) and (col<4 or col>0)):
            print("*",end="")
        else:
            print(end=" ")
    print()
print("\n")
for row in range(6):
    for col in range(7):
        if (col==0 or col==6) or (row<4 and (col==6-row)) or (row<4 and (col==row)):
            print("*",end="")
        else:
            print(" ",end="")
    print()
print("\n")
for row in range(7):
    for col in range(5):
        if (col==0) or ((row==0 or row==3) and (col>0 and col<4)) or ((col==4) and (row>0 and row<3)) or (row-col==2):
            print("*",end=" ")
        else:
            print(end="  ")
    print()
print("\n")
for row in range(7):
    for col in range(5):
        if col==0 or row%3==0:
            print('*', end='')
        else:
            print(end=' ')
    print()

print("\n")
for row in range(7):
    for col in range(5):
        if col==0 or row%3==0:
            print('*', end='')
        else:
            print(end=' ')
    print()
print("\n")
for row in range(6):
    for col in range(6):
        if (col==0 or col==5) or (row==col):
            print("*",end="")
        else:
            print(" ",end="")
    print()

!pip install gTTS

!pip install pillow

import IPython.display as display
from PIL import Image
display.display(Image.open('/samreen.jpg'))
from gtts import gTTS
from IPython.display import Audio
tts = gTTS('Happy birthday Samreen')
tts.save('1.wav')
sound_file = '1.wav'
Audio(sound_file, autoplay=True)